services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./service:/service
    environment:
      DB_HOST: "database"
      DB_NAME: "dbname"
      DB_USER: "dbuser"
      DB_PASS: "pass"

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15.5-bookworm
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "pass"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d dbname" ]
      interval: 5s
      timeout: 3s
      retries: 3

    ports:
      - 5454:5432
